Стилизация страницы каталога + графика
htmlacademy-htmlcss/1402343-sedona-29 pull request #4
Opened 2020-09-22 23:30 UTC by anastasiiguz

Добавилена стилизация каталога; внесены мелкие изменения в стилизацию основной страницы; добавлены контетные изображения в разметку; скачаны все иконки и изображения по макету.

2020-09-23 10:20 UTC, sergeiwerty requested changes
Идёшь с хорошей скоростью! 
По сути подправить не так уж много надо: фон в каталоге отелей, блок "Найдено" и индикаторы сортировки, ну и в социальных кнопках добавить иконки.

2020-09-23 10:20 UTC, sergeiwerty commented on catalog.html
> +    <h2 class="visually-hidden">Форма поиска отелей</h2>
h2 будет очень уместен уже внутри section'a с фильтром

2020-09-23 10:20 UTC, sergeiwerty commented on catalog.html
> +    <section class="filter">
Этому section'y тоже уже нужно изображение-фон

2020-09-23 10:20 UTC, sergeiwerty commented on catalog.html
> +        <li class="hotel-item">
На этом этапе всем отелям уже нужно добавить плашки со "звёздным" рейтингом

2020-09-23 10:20 UTC, sergeiwerty commented on catalog.html
> +        <li><a class="social-button" href="blank.html">Twitter</a></li>
Соответственно и здесь ссылки придётся удалить

2020-09-24 23:36 UTC, anastasiiguz commented on css/style.css
>  body {
В критерии Б13 указано 1200px, я сначала проставила с учетом боковых теней, но потом сверилась и решила по критерию поставить. Как в итоге лучше будет сделать?

2020-09-24 23:49 UTC, anastasiiguz commented on css/style.css
>    background-image: url(../img/background-photo.png);
Фон был задан <p>, в котором были изображения, заменила его на <div>, в таком формате оставлять?

2020-09-25 00:47 UTC, sergeiwerty commented on css/style.css
>  body {
Да, ты права. Извини.
Я слишком забежал вперёд в этом моменте. Всё это поведение будет реализовываться дальше в проекте.

2020-09-25 00:59 UTC, sergeiwerty commented on css/style.css
>    background-image: url(../img/background-photo.png);
Посмотри ещё раз внимательно на селектор. 
![изображение](https://user-images.githubusercontent.com/30851572/94214862-76a86480-fee3-11ea-8da6-cb6d8d8821c9.png)

2020-09-25 11:31 UTC, anastasiiguz commented on css/style.css
>    background-image: url(../img/background-photo.png);
прошу прощения, невнимательно просмотрела , все поправлю)

2020-09-27 14:04 UTC, merged